In [27]:
import pandas as pd
import numpy as np

In [28]:
def CleaningData(filepath,Year):
    get_df = pd.read_csv(filepath)
    
    get_df = get_df[['Province', 'Centre', 'Zone', 'Neighbourhood', 'Dwelling Type ','Bachelor ','1 Bedroom','2 Bedroom', '3 Bedroom +','Total ']]
    
    get_df = get_df.replace("**", 0)
    get_df = get_df.replace("--", 0)
    get_df = get_df.replace("\n"," ", regex = True)
    
    get_df["Province"] = get_df["Province"].str.split("/").str[0]
    get_df["Province"] =get_df["Province"].str.strip()
     
    get_df["Zone"] = get_df["Zone"].str.split("~").str[0]
    get_df["Zone"] = get_df["Zone"].str.strip() 
    get_df["Neighbourhood"] = get_df["Neighbourhood"].str.split("~").str[0]
    get_df["Neighbourhood"] = get_df["Neighbourhood"].str.strip() 
    
    get_df["Dwelling Type "] =get_df["Dwelling Type "].str.split("/").str[0]
    get_df["Dwelling Type "] = get_df["Dwelling Type "].str.strip()
    get_df = get_df[(get_df["Province"] != "Total") & (get_df["Zone"] != "Total") & \
                    (get_df["Neighbourhood"] != "Total") & (get_df["Dwelling Type "] != "Total")]
    
    get_df["Bachelor "] = get_df["Bachelor "].str.replace("%", "",regex=True).replace(",", "",regex=True).astype(float)
    get_df["1 Bedroom"] = get_df["1 Bedroom"].str.replace("%", "",regex=True).replace(",", "",regex=True).astype(float)
    get_df["2 Bedroom"] = get_df["2 Bedroom"].str.replace("%", "",regex=True).replace(",", "",regex=True).astype(float)
    get_df["3 Bedroom +"] = get_df["3 Bedroom +"].str.replace("%", "",regex=True).replace(",", "",regex=True).astype(float)
    get_df["Total "] = get_df["Total "].str.replace("%", "",regex=True).replace(",", "",regex=True).astype(float)
    get_df["Year"] = Year
    
    get_df[["Bachelor ","1 Bedroom","2 Bedroom","3 Bedroom +","Total "]] = get_df[["Bachelor ","1 Bedroom","2 Bedroom","3 Bedroom +","Total "]].apply(pd.to_numeric)
    
    return get_df

In [29]:
filepath_2018 = "Number_of_units_2018.csv"
filepath_2019 = "Number_of_units_2019.csv"
filepath_2020 = "Number_of_units_2020.csv"
filepath_2021 = "Number_of_units_2021.csv"
filepath_2022 = "Number_of_units_2022.csv"


files = [[filepath_2018,2018],[filepath_2019,2019], [filepath_2020,2020],[filepath_2021,2021],[filepath_2022,2022]]
for each in files:
    clean_data = CleaningData(each[0],each[1])
    Output_files = clean_data.to_csv(f"Number_of_units_clean_{each[1]}.csv",index=False)

,Province,Centre,Zone,Neighbourhood,Dwelling Type,Bachelor,1 Bedroom,2 Bedroom,3 Bedroom +,Total,Year
0,Nfld.Lab.,St. John's,St. John's East,St. John's East,Row,1.0,21.0,18.0,17.0,57.0,2022
1,Nfld.Lab.,St. John's,St. John's East,St. John's East,Apt & Other,230.0,708.0,1066.0,106.0,2110.0,2022
2,Nfld.Lab.,St. John's,St. John's West,St. John's West,Row,0.0,47.0,20.0,0.0,67.0,2022
3,Nfld.Lab.,St. John's,St. John's West,St. John's West,Apt & Other,210.0,474.0,862.0,123.0,1669.0,2022
4,Nfld.Lab.,St. John's,Remainder of CMA,Remainder of CMA,Row,0.0,4.0,83.0,6.0,93.0,2022
...,...,...,...,...,...,...,...,...,...,...,...
1785,B.C.,Victoria,Oak Bay,Oak Bay North,Apt & Other,33.0,370.0,283.0,3.0,689.0,2022
1786,B.C.,Victoria,North Saanich,North Saanich,Row,NaN,NaN,NaN,NaN,NaN,2022
1787,B.C.,Victoria,North Saanich,North Saanich,Apt & Other,NaN,NaN,NaN,NaN,NaN,2022
1788,B.C.,Victoria,Sidney,Sidney,Row,NaN,NaN,NaN,NaN,NaN,2022
1789,B.C.,Victoria,Sidney,Sidney,Apt & Other,13.0,248.0,163.0,21.0,445.0,2022

Bachelor         91.435719
1 Bedroom       473.308548
2 Bedroom       676.378040
3 Bedroom +     141.444753
Total          1382.567060
Year           2022.000000
dtype: float64