In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import scipy.stats as st
import numpy as np

In [2]:
#Reading the files
path_rental = "Resources/AverageRents_Concat.csv"
# path_Number_of_Units = pd.re("Resources/Number_of_Units_Concat.csv")
# path_VacancyRate = pd.read_csv("Resources/VacancyRate_Concat.csv")

In [3]:
#identify how provinces are named in the dataset
# print(rental_df["Province"].unique())
rental_df = pd.read_csv(path_rental)
# rental_df.columns

In [4]:
#Create a funtion to extract based on the province and year 
def data_set(filepath,Province,Year,column):
    get_df = pd.read_csv(filepath)
    df = get_df.loc[(rental_df["Year"] == Year )& (get_df["Province"] == Province)]
    df_Province = df[(df[column]!=0)]
    return df_Province

In [5]:
#Check if the function works fine and get the Ont.province
Year = 2022
column = "1 Bedroom"
df_Ontario = data_set(path_rental, "Ont.",Year,column)
df_Ontario

,Province,Centre,Zone,Neighbourhood,Dwelling Type,Bachelor,1 Bedroom,2 Bedroom,3 Bedroom +,Total,Year
7669,Ont.,Barrie,Barrie,Downtown,Apt & Other,1067.0,1294.0,1571.0,1516.0,1412.0,2022
7673,Ont.,Barrie,Barrie,North Barrie,Apt & Other,0.0,1341.0,1516.0,0.0,1423.0,2022
7675,Ont.,Barrie,Barrie,East End,Apt & Other,0.0,1311.0,1464.0,0.0,1398.0,2022
7677,Ont.,Barrie,Barrie,South Barrie,Apt & Other,0.0,1625.0,1804.0,0.0,1746.0,2022
7683,Ont.,Belleville,City of Belleville,Belleville (Southwest),Apt & Other,979.0,1145.0,1340.0,1711.0,1285.0,2022
...,...,...,...,...,...,...,...,...,...,...,...
8347,Ont.,Windsor,East Outer,Fontainebleau,Apt & Other,1044.0,1151.0,1267.0,1426.0,1242.0,2022
8353,Ont.,Windsor,West,University,Apt & Other,742.0,955.0,1080.0,1077.0,984.0,2022
8355,Ont.,Windsor,West,Sandwich,Apt & Other,795.0,962.0,1103.0,0.0,1017.0,2022
8359,Ont.,Windsor,Amherstburg,Amherstburg,Apt & Other,0.0,1165.0,1348.0,0.0,1259.0,2022
8361,Ont.,Windsor,Remainder of CMA,Remainder of CMA,Apt & Other,0.0,1056.0,1190.0,0.0,1124.0,2022

In [6]:
#define Provinces name in the list
Province = ['Ont.']
Province

['Ont.']

In [7]:
# Using the aggregation method, to produce the summary statistics in a single line for all bedrooms in Ontario
aggregation_totalbedrooms= df_Ontario.groupby(['Province'])[['1 Bedroom', '2 Bedroom', '3 Bedroom +']].agg(['mean', 'var', 'std', 'sem'])
aggregation_totalbedrooms.round(2)

         1 Bedroom                        2 Bedroom                            \
              mean       var    std   sem      mean        var     std    sem
Province
Ont.       1306.13  69801.54  264.2  15.6   1516.12  196652.09  443.45  26.18

         3 Bedroom +
                mean        var     std    sem
Province
Ont.         1065.99  931005.31  964.89  56.96

In [8]:
# Rent_mean = df_Ontario.groupby('Province').mean()['1 Bedroom']
# Rent_median = rental_df.groupby('Province').median()['1 Bedroom']
# Rent_variance = rental_df.groupby('Province').var()['1 Bedroom']
# Rent_std = rental_df.groupby('Province').std()['1 Bedroom']
# # # Rent_sem = rental_df.groupby('Province').sem()['1 Bedroom']

# Rent_mean

In [13]:
#Check if the function works fine and get the BC provinces
Year = 2022
column = "1 Bedroom"
df_BC = data_set(path_rental, "B.C.",Year,column)
df_BC

,Province,Centre,Zone,Neighbourhood,Dwelling Type,Bachelor,1 Bedroom,2 Bedroom,3 Bedroom +,Total,Year
8741,B.C.,Abbotsford - Mission,Abbotsford,Mill Lake,Apt & Other,776.0,1160.0,1417.0,0.0,1286.0,2022
8743,B.C.,Abbotsford - Mission,Abbotsford,Abbotsford/McMillan,Apt & Other,834.0,1052.0,1327.0,0.0,1149.0,2022
8745,B.C.,Abbotsford - Mission,Abbotsford,Townline/Clearbrook,Apt & Other,858.0,1121.0,1299.0,1734.0,1212.0,2022
8749,B.C.,Abbotsford - Mission,Abbotsford,Whatcom/Sumas,Apt & Other,1350.0,1435.0,1808.0,0.0,1595.0,2022
8751,B.C.,Abbotsford - Mission,Mission,Mission,Apt & Other,0.0,1010.0,1179.0,0.0,1075.0,2022
...,...,...,...,...,...,...,...,...,...,...,...
8937,B.C.,Victoria,Langford/Vw Royal/Colwood/Sooke,Langford,Apt & Other,1364.0,1592.0,1915.0,2197.0,1756.0,2022
8939,B.C.,Victoria,Langford/Vw Royal/Colwood/Sooke,Colwood,Apt & Other,0.0,1226.0,1495.0,0.0,1365.0,2022
8943,B.C.,Victoria,Oak Bay,Oak Bay South,Apt & Other,0.0,1282.0,1732.0,0.0,1542.0,2022
8945,B.C.,Victoria,Oak Bay,Oak Bay North,Apt & Other,1107.0,1226.0,1679.0,0.0,1405.0,2022
8949,B.C.,Victoria,Sidney,Sidney,Apt & Other,0.0,1447.0,1753.0,3093.0,1635.0,2022

In [12]:
# Using the aggregation method, to produce the summary statistics in a single line for all bedrooms in British Columbia
aggregation_totalbedrooms= df_BC.groupby(['Province'])[['1 Bedroom', '2 Bedroom', '3 Bedroom +']].agg(['mean', 'var', 'std', 'sem'])
aggregation_totalbedrooms.round(2)

         1 Bedroom                          2 Bedroom                     \
              mean       var     std    sem      mean        var     std
Province
B.C.       1442.67  65487.77  255.91  25.98   1815.99  325572.45  570.59

                3 Bedroom +
            sem        mean         var      std     sem
Province
B.C.      57.93     1265.72  1856171.43  1362.41  138.33